// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform != TargetPlatform.iOS) {
      throw UnsupportedError('Kotrana Firebase is configured for iOS only.');
    }
    return ios;
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjBZnkd14HSTDIblB9OrTu5X9xLyBECc',
    appId: '1:642732716369:ios:0ca6bdca53439e5dc2a370',
    messagingSenderId: '642732716369',
    projectId: 'myappv4',
    databaseURL: 'https://myappv4.firebaseio.com',
    storageBucket: 'myappv4.firebasestorage.app',
    iosClientId:
        '642732716369-r3epuls5j2agmsicp0u4ufggpndaarqm.apps.googleusercontent.com',
    iosBundleId: 'dev.mamy-r.kotrana',
  );
}
